name: Backend CI/CD p

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    name: Deploy Backend to DEV
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: backend

      - name: Deploy to DEV slot
        uses: azure/webapps-deploy@v3
        with:
          app-name: backend-devops-assignment
          slot-name: dev
          publish-profile: ${{ secrets.AZURE_BACKEND_PUBLISH_PROFILE }}
          package: ./backend

  promote-staging:
    name: Promote DEV → STAGING
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Slot swap DEV → STAGING
        run: |
          az webapp deployment slot swap \
            --resource-group rg-app \
            --name backend-devops-assignment \
            --slot dev \
            --target-slot staging

  promote-prod:
    name: Promote STAGING → PROD
    needs: promote-staging
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Slot swap STAGING → PROD
        run: |
          az webapp deployment slot swap \
            --resource-group rg-app \
            --name backend-devops-assignment \
            --slot staging \
            --target-slot production
